#!/usr/bin/env python3
"""Regenerate configs/tuning_split.yaml — the held-out split every method's
hyper-parameters are fitted on.

The split is a **different ContactPose participant** from the evaluation set, so
tuning never sees an evaluation grasp, nor even the same hand.  Objects are
spread evenly over the solidity range the two participants share, so the tuning
grasps span the same easy-to-concave spectrum as the benchmark.

    python scripts/make_tuning_split.py --grasps <grasps_root>
"""
import argparse

import numpy as np
import yaml

from toporetarget.contactpose import list_objects
from toporetarget.paths import CONFIGS

N_OBJECTS = 8


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grasps", required=True)
    ap.add_argument("--participant", default="full15")
    ap.add_argument("--intent", default="use")
    ap.add_argument("--eval-set", default=str(CONFIGS / "eval_set.yaml"))
    ap.add_argument("--out", default=str(CONFIGS / "tuning_split.yaml"))
    args = ap.parse_args()

    eval_cfg = yaml.safe_load(open(args.eval_set))
    if args.participant == eval_cfg["participant"]:
        raise SystemExit("the tuning participant must differ from the evaluation one")
    solidity = {o: s["solidity"] for o, s in eval_cfg["object_stats"].items()}

    tune_objects = list_objects(args.grasps, args.participant, args.intent)
    common = sorted((o for o in tune_objects if o in solidity), key=lambda o: solidity[o])
    picks = [common[i] for i in np.linspace(0, len(common) - 1, N_OBJECTS).round().astype(int)]

    cfg = dict(
        purpose="Held-out split for fitting every method's hyper-parameters.",
        participant=args.participant, intent=args.intent, hand="right",
        disjoint_from=dict(participant=eval_cfg["participant"],
                           note=("a DIFFERENT person: different hand geometry and "
                                 "different grasp style, so no evaluation grasp is "
                                 "ever seen during tuning")),
        selection=(f"{N_OBJECTS} objects spread evenly over the solidity range "
                   f"shared by both participants"),
        objects=sorted(picks),
        solidity={o: solidity[o] for o in sorted(picks)},
    )
    with open(args.out, "w") as f:
        f.write("# Frozen tuning split - generated by scripts/make_tuning_split.py, "
                "do not hand-edit.\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    print(f"{args.participant}_{args.intent}: {len(common)} shared objects -> "
          f"{picks} written to {args.out}")


if __name__ == "__main__":
    main()
