#!/usr/bin/env python3
"""Regenerate a viewer directory's manifest.js from the payloads present.

The viewer loads whatever this lists, so it must describe files that actually
exist — otherwise the page requests a payload that was never committed (dataset
derived ones are git-ignored).

    python scripts/make_viewer_manifest.py [viewer_dir]
"""
import argparse
import json
from pathlib import Path

# Payloads derived from licence-gated datasets are git-ignored, so the manifest
# that ships must not name them: a fresh clone would request files it does not
# have.  The viewer tolerates a missing payload, but the 404s are noise.
UNSHIPPED = ("data_grab_", "data_contactpose_")


def label_of(payload: Path) -> str:
    """Prefer the label the exporter stored in the payload's metadata."""
    key = payload.stem[len("data_"):]
    try:
        meta = json.loads(payload.read_text().partition(" = ")[2].rstrip().rstrip(";"))
        return str(meta["meta"]["label"])
    except Exception:
        return key.replace("_", " ")


def build(directory, shipped_only=False) -> list:
    d = Path(directory)
    payloads = sorted(d.glob("data_*.js"))
    if shipped_only:
        payloads = [p for p in payloads if not p.name.startswith(UNSHIPPED)]
    entries = [dict(key=p.stem[len("data_"):],
                    var="TR_" + p.stem[len("data_"):].upper(),
                    file=p.name, label=label_of(p))
               for p in payloads]
    (d / "manifest.js").write_text(
        "// Generated by scripts/make_viewer_manifest.py - do not hand-edit.\n"
        "window.TR_MANIFEST = " + json.dumps(entries) + ";")
    return entries


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("directory", nargs="?", default="viewer")
    ap.add_argument("--shipped-only", action="store_true",
                    help="list only payloads that are committed (excludes the "
                         "git-ignored dataset ones)")
    args = ap.parse_args()
    found = build(args.directory, args.shipped_only)
    print(f"{args.directory}/manifest.js: {[e['key'] for e in found] or 'no payloads'}")
